### ISSUE TITLE
Review environments not cleaned up if branch is deleted too quickly

### ISSUE THREAD

**Issue by pushred** [SparkartGroupInc/qa-deployer#13]
In #6 qa-deployer will shutdown any Modulus projects running if an open PR isn't found. But this is intended to be run in a CircleCI build, triggered by the pull request's closure. The problem with this is that if the branch is deleted at the same time the PR is closed, as GitHub and general best practices [effectively recommend][1], the CircleCI build will [fail to start][2].

How about adding a check whenever any builds are running for any running projects that designated for production, and don't have a matching pull request? This would still miss some projects for sites that aren't updated frequently, but it should overall.

[1]: https://help.github.com/articles/deleting-unused-branches/
[2]:  https://zapier.com/app/history/ee84da07-dbec-4419-940c-be7fb008f434

**Comment by joanniclaborde** [comment]
I confirmed with CircleCI support that it's impossible to run a post-branch-delete build. That would have been the cleanest solution.

Instead, think I'll create a new qa-deployer script, `circleci-cleanup`, that can be run after `circleci-deploy` (I don't want to automatically delete projects when deploying, sounds too much like a hidden side-effect). This script will list all closed pull requests, and "withdraw" all matching projects with the current deployer settings. I could also withdraw all projects not matching an open pull request, but it's probably too aggressive...
