### ISSUE TITLE
S3 deploys not purging CDN cache

### ISSUE THREAD

**Issue by pushred** [SparkartGroupInc/qa-deployer#14]
How are the pages deployed to S3 currently configured in re: to expiration? There have been a couple of instances where a successful deploy fails to purge the Edgecast CDN in a timely manner.

**Comment by joanniclaborde** [comment]
No Cache-Control/Pragma/Expires headers are returned at all by S3, and this is EdgeCast's behaviour in this case:

> If none of the above headers are included with the response from the origin server, then the requested content will be cached for 7 days, by default, on the POP handling the request and by the requesting client's user agent.

s3-site has a [`noCache`](https://github.com/firstopinion/s3-site/blob/master/lib/bucket.js#L291) option, but we don't want to use that, obviously. So we can:

1. Add a feature to s3-site to specify a relatively short TTL, like 1 hour
2. Manually purge EdgeCast after a deploy
3. Add a notifier to qa-deployer that purges EdgeCast

**Comment by pushred** [comment]
What about etags? Does Edgecast support them? That would identify each set of files and ideally purge immediately? Or, setting Expires header for the date/time of the deploy?

**Comment by joanniclaborde** [comment]
Etags are returned by S3, but EdgeCast needs to poll the server for that to work. And it does it every 7 days.

EdgeCast won't know about Expires headers for up to 7 days, for that same reason.

**Comment by pushred** [comment]
I see, guess we don't have a choice other than to purge Edgecast manually then.

**Comment by joanniclaborde** [comment]
In order to purge EdgeCast, we need to send a PUT request to their API:
```
PUT:
  https://api.edgecast.com/v2/mcc/customers/[EDGECAST_ACCOUNT_ID]/edge/purge
HEADERS:
  {'Authorization' => "TOK:#{EDGECAST_API_TOKEN}",
   'Host'          => 'api.edgecast.com',
   'Accept'        => 'application/json',
   'Content-Type'  => 'application/json'}
BODY:
  {'MediaPath' => 'CDN or edge CNAME URL to purge',
   'MediaType' => 8} // 2: Flash Media Streaming, 3: HTTP Large, 8: HTTP Small, 14: Application Delivery Network (ADN)
```

We can either use the webhook notifier to send a request to Zapier, which will take care of the EdgeCast request, or modify the webhook notifier so it does the EdgeCast request itself. We'll need to add support for new `method` and `headers` options for this to work. Got a preferred solution?

**Comment by joanniclaborde** [comment]
The only problem with purging directly with qa-deployer is that EDGECAST_API_TOKEN needs to be hardcoded in Broadway. Or added to CircleCI's env variables.

**Comment by pushred** [comment]
Env would be consistent with the GitHub notifier, no reason to break with that really.
