### ISSUE TITLE
Package name fallback for project/bucket_name config

### ISSUE THREAD

**Issue by pushred** [SparkartGroupInc/qa-deployer#9]
I've got a series of projects where I'd like to reuse my deployer config files, loading them from a library module rather than locally to the project. The only thing stopping me are the `project` and `bucket_name` properties. It's fine to omit these for review URLs, but for production they need to match specific Modulus projects and S3 buckets.

In S3 that bucket must match the domain I want to use, and in Modulus I follow a convention of naming the project with the primary domain. I also follow that convention for naming the project's own package, the repository, etc. I know I'm not alone there, [GitHub Pages][1] is a similar example.

So how about allowing the package's name to be used if none is specified? If a Modulus project or S3 bucket doesn't exist with the name specified or the package's name, _then_ a project/bucket would be created.

[1]: https://pages.github.com

**Comment by joanniclaborde** [comment]
This can work, I'll modify the deployers to automatically use the package's name when no project/bucket is specified, and also the CircleCI scripts to NOT generate a name when the current branch is `master`.
